name: Update Waka README

on:
  schedule:
    # Atualiza diariamente às 19:00 UTC
    - cron: '00 19 * * *'
  workflow_dispatch: # Permite que o workflow seja acionado manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: "true"
          SHOW_PROJECTS: "true"
          SHOW_EDITORS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_COMMIT: "true"
          SHOW_LANGUAGE: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_LOC_CHART: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_PROFILE_VIEWS: "true"
          SHOW_SHORT_INFO: "true"
          COMMIT_BY_ME: "true"
          IGNORED_REPOS: ""
