name: Update README with Date and Coding Stats

on:
  push:
    branches:
      - main
  schedule:
    # Atualiza diariamente às 18:30 UTC
    - cron: '30 18 * * *'
  workflow_dispatch: # Permite que o workflow seja acionado manualmente

jobs:
  update-readme:
    name: Update Readme with Date and Coding Stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README with Date
        run: |
          current_date=$(date +"%d-%m-%Y %H:%M:%S")
          sed -i "s/Última atualização em.*/Última atualização em $current_date UTC/" README.md

      - name: Update README with WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated README with current date and WakaTime stats"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
