name: Update Waka README

on:
  schedule:
    # Atualiza diariamente às 19:00 UTC
    - cron: '00 19 * * *'
  workflow_dispatch: # Permite que o workflow seja acionado manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: "false"
          SHOW_EDITORS: "false"
          SHOW_LOC_CHART: "false"
          SHOW_TOTAL_CODE_TIME: "false"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_LINES_OF_CODE: "false"
          SHOW_PROJECTS: "false"
          SHOW_TIMEZONE: "false"
          SHOW_SHORT_INFO: "false"
