name: Update README with Current Date

on:
  schedule:
    # Atualiza diariamente às 18:30 UTC
    - cron: '30 18 * * *'
  workflow_dispatch: # Permite que o workflow seja acionado manualmente

jobs:
  update-readme:
    name: Update Readme with Current Date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          current_date=$(date +"%d-%m-%Y %H:%M:%S")
          sed -i "s/Última atualização em.*/Última atualização em $current_date UTC/" README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated README with current date"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Token para autenticação
