name: Update Waka README

on:
  push:
    branches:
      - main
  schedule:
    # Atualiza diariamente às 19:00 UTC
    - cron: '00 19 * * *'
  workflow_dispatch: # Permite que o workflow seja acionado manualmente

jobs:
  update-readme:
    name: Update Readme with Date and Coding Stats
    runs-on: ubuntu-latest

    steps:
      - name: Update README with WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated README with current date and WakaTime stats"
          git push
