name: Update Waka README

on:
  schedule:
    # Atualiza diariamente às 19:00 UTC
    - cron: '00 19 * * *'
  workflow_dispatch: # Permite que o workflow seja acionado manualmente

jobs:
  update-readme:
    name: Update Readme with Date and Coding Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
